FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y g++
RUN apt-get install -y libpq-dev
RUN apt-get install -y pkg-config

WORKDIR /usr/src/app
COPY main.cpp .
COPY Database.h .
COPY Database.cpp .
RUN g++ -o main main.cpp Database.cpp $(pkg-config --cflags --libs libpq)

CMD ["./main"]